### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by HarvsG** [finzzz/wgzero#1]
Thanks for this, looks great.

Would be great to add the following options, although I appreciate this work is deliberately un-bloated.
1. Add option to specify server private key. This would help with transfering installations and/or allowing devices that are already 'clients' of another network to become 'servers'
2. Add option to specify allowed IPs for each new client, this would make it easier to set up site-to-site networks

IMO this could be added a flags rather than prompts, keeping the plain install very short.

**Comment by finzzz** [comment]
Hey!

Thanks for the bug report and suggestions. I would consider it. 
Feel free to submit pull request.

**Comment by finzzz** [comment]
For now, I have added the option to change DNS and allowed IPs. I am not sure about changing server public key though, because the other configs should be changed. Can't you just edit it manually assuming most people would not need this feature? Or maybe tell me more specific about the use case you are thinking?

**Comment by finzzz** [comment]
I have implemented your suggestions. Sorry for not merging your last pull request.  
I'm not sure if flag options will be implemented in the near future. For now, I will close this issue.
